# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8082
  servlet:
    context-path: /renren-admin
    session:
      cookie:
        http-only: true
netty:
  port: 9099
  isRecord: record
  websocket:
    port: 8888

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  messages:
    encoding: UTF-8
    basename: i18n/messages
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    database: 0
    host: 192.168.10.10
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  main:
    allow-bean-definition-overriding: true


knife4j:
  enable: true
  basic:
    enable: false
    username: admin
    password: admin
  setting:
    enableFooter: false


flowable:
  activity-font-name: \u5B8B\u4F53
  label-font-name: \u5B8B\u4F53
  annotation-font-name: \u5B8B\u4F53
  async-executor-activate: false
  check-process-definitions: false
  db-history-used: true
  history-level: full
  database-schema-update: true


fdfs:
  so-timeout: 600000
  connect-timeout: 6000
  tracker-list: #TrackerList参数,支持多个
    - 192.168.10.10:22122

# 是否开启redis缓存  true开启   false关闭
renren:
  redis:
    open: false

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml,classpath:/META-INF/modeler-mybatis-mappings/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.renren.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型
      id-type: ASSIGN_ID
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
  #服务器域名地址
  server.service-domain: http://127.0.0.1:8080
  
  #微信app支付
  pay.wxpay.app.appID: "你的appid"
  pay.wxpay.app.mchID: "你的商户id"
  pay.wxpay.app.key: "你的api秘钥，不是appSecret"
  #从微信商户平台下载的安全证书存放的路径、我放在resources下面,切记一定要看看target目录下的class文件下有没有打包apiclient_cert.p12文件
  pay.wxpay.app.certPath: static/cert/wxpay/apiclient_cert.p12
  #微信支付成功的异步通知接口
  pay.wxpay.app.payNotifyUrl: ${server.service-domain}/api/wxPay/notify